{% set name = "PyBIS" %}
{% set version = "1.37.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc4d281b2d7fb32edf035fcec988e1f07a79da3491b442ad4630cc9b116ea131

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pandas
    - pytest
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - tabulate
    - texttable
    - urllib3

test:
  imports:
    - pybis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://sissource.ethz.ch/sispub/openbis/tree/master/api-openbis-python3-pybis
  summary: openBIS connection and interaction, optimized for using with Jupyter
  license: Apache-2.0
  license_file: LICENSE
  description: |
    pyBIS is a Python module for interacting with openBIS. pyBIS is
    designed to be most useful in a Jupyter Notebook or IPython
    environment, especially if you are developing Python scripts for
    automatisation. Jupyter Notebooks offer some sort of IDE for
    openBIS, supporting TAB completition and immediate data checks,
    making the life of a researcher hopefully easier.
  doc_url: https://sissource.ethz.ch/sispub/openbis/tree/master/api-openbis-python3-pybis/src/python

extra:
  recipe-maintainers:
    - fabianegli
    - laskadam
