{% set name = "PyBIS" %}
{% set version = "1.35.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fd0d238966ab309d7e402d7938a643d4370c5df73f37da5c6fe69d44012363e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - pytest
    - python >=3.6
    - python-dateutil
    - requests
    - tabulate
    - texttable
    - urllib3

test:
  imports:
    - pybis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sissource.ethz.ch/sispub/openbis/tree/master/pybis
  summary: openBIS connection and interaction, optimized for using with Jupyter
  license: Apache-2.0
  license_file: LICENSE
  description: |
    pyBIS is a Python module for interacting with openBIS. pyBIS is
    designed to be most useful in a Jupyter Notebook or IPython
    environment, especially if you are developing Python scripts for
    automatisation. Jupyter Notebooks offer some sort of IDE for
    openBIS, supporting TAB completition and immediate data checks,
    making the life of a researcher hopefully easier.
  doc_url: https://sissource.ethz.ch/sispub/openbis/-/tree/master/pybis/src/python

extra:
  recipe-maintainers:
    - fabianegli
